### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ruscon** [m3talstorm/foe-bot#17]
```bash
pip install -r requirements.txt
Collecting requests==2.9.1 (from -r requirements.txt (line 1))
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting pydash (from -r requirements.txt (line 2))
  Using cached pydash-4.3.0-py2.py3-none-any.whl
Collecting moment (from -r requirements.txt (line 3))
  Using cached moment-0.8.2.tar.gz
Collecting sqlalchemy (from -r requirements.txt (line 4))
  Using cached SQLAlchemy-1.1.15.tar.gz
Collecting anyconfig (from -r requirements.txt (line 5))
  Using cached anyconfig-0.9.3.tar.gz
Collecting pyyaml (from -r requirements.txt (line 6))
  Using cached PyYAML-3.12.tar.gz
Collecting dateparser>=0.6 (from moment->-r requirements.txt (line 3))
  Using cached dateparser-0.6.0-py2.py3-none-any.whl
Collecting pytz>=2017.2 (from moment->-r requirements.txt (line 3))
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting times (from moment->-r requirements.txt (line 3))
  Using cached times-0.7-py2.py3-none-any.whl
Collecting tzlocal (from dateparser>=0.6->moment->-r requirements.txt (line 3))
  Using cached tzlocal-1.5.tar.gz
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dateparser>=0.6->moment->-r requirements.txt (line 3))
Collecting ruamel.yaml (from dateparser>=0.6->moment->-r requirements.txt (line 3))
  Using cached ruamel.yaml-0.15.34.tar.gz
    Complete output from command python setup.py egg_info:
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fq/vv2xnzwd1qgck76jswx_yb6w0000gn/T/pip-build-Q8TxS8/ruamel.yaml/setup.py", line 917, in <module>
        main()
      File "/private/var/folders/fq/vv2xnzwd1qgck76jswx_yb6w0000gn/T/pip-build-Q8TxS8/ruamel.yaml/setup.py", line 905, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fq/vv2xnzwd1qgck76jswx_yb6w0000gn/T/pip-build-Q8TxS8/ruamel.yaml/
```

**Comment by ruscon** [comment]
in my mac os 
```
sudo pip install --user --upgrade setuptools
sudo pip install --user -r requirements.txt
```
