### ISSUE TITLE
python main.py fail

### ISSUE THREAD

**Issue by ruscon** [m3talstorm/foe-bot#18]
```
➜  foe git:(master) ✗ python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from models.account import Account
  File "/Users/user/Games/foe-bot/foe/models/account.py", line 17, in <module>
    from request import Request
  File "/Users/user/Games/foe-bot/foe/request.py", line 13, in <module>
    from config import config
  File "/Users/user/Games/foe-bot/foe/config.py", line 18, in <module>
    config = anyconfig.load([DEFAULT, PATH])
  File "/Library/Python/2.7/site-packages/anyconfig/api.py", line 373, in load
    **options)
  File "/Library/Python/2.7/site-packages/anyconfig/api.py", line 323, in multi_load
    ac_parser = find_loader(paths[0], ac_parser, is_path(paths[0]))
  File "/Library/Python/2.7/site-packages/anyconfig/api.py", line 145, in find_loader
    is_path_=is_path_)
  File "/Library/Python/2.7/site-packages/anyconfig/backends.py", line 265, in find_parser
    raise UnknownFileTypeError(path_or_stream)
anyconfig.backends.UnknownFileTypeError: No parser found for file './config/foe.yml'
```

Any ideas ?

**Comment by m3talstorm** [comment]
`pip install pyyaml`

**Comment by ruscon** [comment]
Thanks, helped.

In the config I registered a new user_key and sid
But it does not work :)

```
➜  foe git:(master) ✗ python main.py
Deploy: Dropped database
Deploy: Initialized database
Deploy: Committing to database...
Deploy: Committed to database in 0.00s
Account None (None) fetching...
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    account.fetch()
  File "/Users/user/Games/foe-bot/foe/models/account.py", line 77, in fetch
    data = self.request('getData', [])
  File "/Users/user/Games/foe-bot/foe/models/model.py", line 129, in request
    response = Request.request(payload)
  File "/Users/user/Games/foe-bot/foe/request.py", line 85, in request
    raise Exception(message)
Exception: Sorry, an internal error occurred. Please try again later
```

**Comment by m3talstorm** [comment]
Check inside of `foe/config/foe.yml`, this is running 1.113, think they are on 1.115 at the moment.

Check [foe-decryption](https://github.com/m3talstorm/foe-decryption) for the latest version and key.

**Comment by ruscon** [comment]
You are right, I needed to change the secret key
It's working, thanks!
