### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ophott** [m3talstorm/foe-bot#4]
C:\Users\Mayank\Desktop\foe-bot-master\foe>python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from models.account import Account
  File "C:\Users\Mayank\Desktop\foe-bot-master\foe\models\account.py", line 17, in <module>
    from request import Request
  File "C:\Users\Mayank\Desktop\foe-bot-master\foe\request.py", line 13, in <module>
    from config import config
  File "C:\Users\Mayank\Desktop\foe-bot-master\foe\config.py", line 18, in <module>
    config = anyconfig.load([DEFAULT, PATH])
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\api.py", line 373, in load
    **options)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\api.py", line 329, in multi_load
    ac_template=ac_template, ac_context=cnf, **opts)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\api.py", line 262, in single_load
    cnf = psr.load(path_or_stream, **options)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\backend\base.py", line 266, in load
    cnf = self.load_from_path(path_or_stream, container, **options)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\backend\base.py", line 453, in load_from_path
    return self.load_from_stream(self.ropen(filepath), container, **kwargs)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\backend\base.py", line 75, in wrapper
    return func(*args[1:], **kwargs)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\backend\yaml.py", line 182, in _yml_load
    ret = _yml_fnc("load", stream, **_filter_from_options("ac_dict", options))
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anyconfig\backend\yaml.py", line 162, in _yml_fnc
    return fnc(*args, **_filter_from_options(key, options))
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\main.py", line 522, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\constructor.py", line 100, in get_single_data
    node = self.composer.get_single_node()
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ruamel\yaml\parser.py", line 549, in parse_block_mapping_key
    token.start_mark)
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "config\foe.yml", line 5, column 1
expected <block end>, but found '<block mapping start>'
  in "config\foe.yml", line 17, column 5

**Comment by DanAtkinson** [comment]
Can you upload your foe.yml with the user_key and sid values removed?
